export const API_URL = 'http://localhost:3000';

export const GET_REQUESTS_REQUEST = 'GET_REQUESTS_REQUEST';
export const GET_REQUESTS_SUCCESS = 'GET_REQUESTS_SUCCESS';
export const GET_REQUESTS_FAILURE = 'GET_REQUESTS_FAILURE';

export const ADD_REQUEST_REQUEST = 'ADD_REQUEST_REQUEST';
export const ADD_REQUEST_SUCCESS = 'ADD_REQUEST_SUCCESS';
export const ADD_REQUEST_FAILURE = 'ADD_REQUEST_FAILURE';
